CFLAGS=-I../../lib/lmic
LDFLAGS=-lwiringPi

ABP: ABP.cpp
	cd ../../lib/lmic && $(MAKE)
	$(CC) $(CFLAGS) -o ABP ABP.cpp ../../lib/lmic/*.o $(LDFLAGS)

all: ABP

.PHONY: clean

clean:
	rm -f *.o ABP
